### ISSUE TITLE
Can't train external NER model on RONEC corpus using Spacy

### ISSUE THREAD

**Issue by luminitavoicu** [dumitrescustefan/ronec#2]
Hello,

I attempted to use the RONEC corpus with Spacy for NER and I encountered some problems while following the tutorial for using Spacy with RONEC: 

## 1
I cloned the repository and I tried to obtain the .json train and dev files using the `convert_conllubio.py` script and Spacy's convert tool as shown in the tutorial:

`!python3 ronec/spacy/train-local-model/convert_conllubio.py ronec/ronec/conllup/raw/ronec.conllup .`

`!python -m spacy convert train_ronec.conllubio . --converter conllubio`

When I ran the second command, for the train data set I got this error:

> Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/spacy/__main__.py", line 33, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/plac_core.py", line 367, in call
    cmd, result = parser.consume(arglist)
  File "/usr/local/lib/python3.6/dist-packages/plac_core.py", line 232, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/spacy/cli/convert.py", line 106, in convert
    no_print=no_print,
  File "/usr/local/lib/python3.6/dist-packages/spacy/cli/converters/conllu2json.py", line 25, in conllu2json
    for i, (raw_text, tokens) in enumerate(conll_tuples):
  File "/usr/local/lib/python3.6/dist-packages/spacy/cli/converters/conllu2json.py", line 68, in read_conllx
    id_, word, lemma, pos, tag, morph, head, dep, _1, iob = parts
ValueError: too many values to unpack (expected 10)

When I looked at the `train_ronec.conllubio` file, I noticed that there were 11 columns on the first line instead of 10, as shown below:

> 1	Tot	tot	ADV	Rp	_	3	advmod	_	_	*

I found that deleting the "*" on the first line solved this problem, but I couldn't really understand why this happened.

## 2
By observing the .json dev and train output files, I noticed that the "ner" field was missing from the train file.
Here is the representation of a word from the dev file:

> {
                "id":0,
                "orth":"Tinerii",
                "tag":"Ncmpry",
                "head":35,
                "dep":"nsubj:pass",
                "ner":"U-PERSON"
              }

Here is a representation of a word from the train file:
> {
                "id":35,
                "orth":"ROMANIA",
                "tag":"Np",
                "head":-2,
                "dep":"nmod"
              }

## 3
I moved on with the tutorial and I attempted to train the open-source BILSTM-CNN model found here: [https://github.com/kamalkraj/Named-Entity-Recognition-with-Bidirectional-LSTM-CNNs](url) with Spacy's train tool. I cloned the repo and I used the command below to train:

`!python3 -m spacy train ro Named-Entity-Recognition-with-Bidirectional-LSTM-CNNs/models/ train_ronec.json dev_ronec.json -p ner`

I noticed a very strange behavior for this: the model got stuck at 36%, no matter how much time I let it run. This is the output I got:

> Training pipeline: ['ner']
Starting with blank model 'ro'
Counting training words (limit=0)
Itn  NER Loss   NER P   NER R   NER F   Token %  CPU WPS
36% 58105/159192 [00:10<00:16, 6216.60it/s]

I tried a few more times and the behavior did not change: it always stopped progressing at around 30-36%. Since it did not return any errors, I am not sure how to debug it, or if I am using it right.

## Environment

I am running this on Google Colab. Here is some information about the environment:
* spaCy version:** 2.2.4
* Platform:** Linux-4.19.104+-x86_64-with-Ubuntu-18.04-bionic
* Python version:** 3.6.9

**Comment by avramandrei** [comment]
Hi,

We have been looking at your problem and it looks like spaCy modified its conversion scripts. Because of that "*" typo (sorry for that) on the second line, it could not correctly parse the CoNNL-U file and threw the above errors. We modified the `convert_conllubio.py` script. Could you reclone the repository, redo the steps in the tutorial and tell us if it works for you?

**Comment by luminitavoicu** [comment]
Hi,

It works now. Thank you so much for your help!
