### ISSUE TITLE
 ronec question

### ISSUE THREAD

**Issue by misu200** [dumitrescustefan/ronec#3]
Hello,

I ve tried to use RONEC in SpaCy for the following legal text from Romanian Official Gazette: 

> "Aprobă revocarea din calitatea de cenzor a următoarelor persoane: IORGA RADU-GABRIEL,GUCEANU DORINA și TEAHA RODICA și aprobă numirea în calitate de auditor financiar al societatii ARYA CONSULTING S.R.L.,CUI  41617624,J23/3968/2019, pentru o perioadă de 2 ani."

..and I ve got the following result:

> persoane 56 64 PERSON
> IORGA RADU 66 76 ORGANIZATION
> GABRIEL 77 84 ORGANIZATION
> TEAHA RODICA 103 115 ORGANIZATION
> ARYA CONSULTING S.R.L.,CUI   181 209 ORGANIZATION
> 41617624,J23/3968/2019 209 231 NUMERIC_VALUE
> 2 ani 254 259 DATETIME

I am guessing the legal text from Official Gazette looks very different from the one in RONEC . Would I need to create a completely new annotated corpus from Official Gazette or just add to the existing RONEC more annotated legal stuff?

Thanks,
Mihai

**Comment by dumitrescustefan** [comment]
Hi, 

 Because persons are in CAPS and there's no training data like this, it incorrectly says they are ORGs (which are mostly CAPS). Also some tokenization would help, like a space after the commas. 

I'd go for adding more annotated legal stuff, it would provide better results.
