### ISSUE TITLE
No compatible models found for v2.3.4 of spaCy

### ISSUE THREAD

**Issue by ibuda** [dumitrescustefan/ronec#4]
Hi,

When I try to download **RONEC** copus by running:  
`python3 -m spacy download ro_core_news_sm`
I am getting the following error:
`No compatible models found for v2.3.4 of spaCy`
This happens also when I try to follow the download commands from this [link](https://spacy.io/universe/project/ronec).

On a second note, I would like to thank you for your work in bringing the **RONEC** corpus to the world, any of your guidance would be much appreciated.

**Comment by ibuda** [comment]
Ok, I found a way to get around that error by finding the latest at the moment version of RONEC [here](https://github.com/explosion/spacy-models/releases/):
ro_core_news_sm-3.0.0a0
Then I just ran the command to install it:
`pip3 install https://github.com/explosion/spacy-models/releases/download/ro_core_news_sm-3.0.0a0/ro_core_news_sm-3.0.0a0.tar.gz  `
and everything worked like a charm.
Once again, thank you for your input into **RONEC**.

**Comment by dumitrescustefan** [comment]
Hi, sorry for responding late, it was a busy week. I'm glad you got it to work, RONEC v1 (we're aiming for a v2 early next year) should be integrated in spacy v3 natively, so you wouldn't have to bother with other files/commands. 
Thank you for your appreciation!
